// Compiles src/client/index.tsx → src/client-bundle.ts (auto-generated, do not edit directly)
import { build } from 'esbuild';
import { writeFileSync } from 'fs';

const result = await build({
  entryPoints: ['src/client/index.tsx'],
  bundle: true,
  minify: true,
  write: false,
  format: 'iife',
  target: ['es2022'],
  jsx: 'automatic',
  jsxImportSource: 'react',
  tsconfig: 'src/client/tsconfig.json',
});

const js = result.outputFiles[0].text;
writeFileSync(
  'src/client-bundle.ts',
  `// Auto-generated by build-client.mjs — edit src/client/ instead\nexport const CLIENT_SCRIPT = ${JSON.stringify(js)};\n`,
);

console.log('[dashboard] client bundle generated (' + js.length + ' bytes)');
